name: emd_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  freezed_annotation: ^2.4.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  gap: ^3.0.1
  google_maps_flutter: ^2.2.8
  flutter_stripe: ^10.2.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  geocoding_platform_interface: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
